runtime: python311
env: flex

env_variables:
  FLASK_ENV: production

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

entrypoint: python backend/start.py 